name: Deploy to GitHub Pages

# 設定觸發條件，當 push 到 main 分支時執行此 workflow
on:
  push:
    branches:
      - main

# 設定執行權限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢查程式碼
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: 設定 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 使用你專案需要的 Node.js 版本

      # Step 3: 安裝依賴
      - name: Install dependencies
        run: npm install

      # Step 4: 建置 Vue 專案
      - name: Build
        run: npm run build

      # Step 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 建置後的檔案位於 dist 目錄
